// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using infra.Persistence;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(_dbContext))]
    [Migration("20240306074442_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("domain.Entities.PDPA.PdpaConsent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Con_Code");

                    b.Property<DateTime?>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("CreatorUserId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DeleterUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescriptionEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DescriptionEN");

                    b.Property<string>("DescriptionTh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DescriptionTH");

                    b.Property<string>("DescriptionZh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DescriptionZH");

                    b.Property<decimal>("IsDeleted")
                        .HasColumnType("decimal(20,0)");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("LastModifierUserId")
                        .HasColumnType("bigint");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TitleEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TitleEN");

                    b.Property<string>("TitleTh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TitleTH");

                    b.Property<string>("TitleZh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TitleZH");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("PdpaConsents");
                });

            modelBuilder.Entity("domain.Entities.PDPA.PdpaPrivacy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("CreatorUserId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DeleterUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescriptionEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DescriptionEN");

                    b.Property<string>("DescriptionTh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DescriptionTH");

                    b.Property<string>("DescriptionZh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DescriptionZH");

                    b.Property<decimal>("IsDeleted")
                        .HasColumnType("decimal(20,0)");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("LastModifierUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("PpCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("PP_Code");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TitleEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TitleEN");

                    b.Property<string>("TitleTh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TitleTH");

                    b.Property<string>("TitleZh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TitleZH");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("PdpaPrivacyPolicies");
                });

            modelBuilder.Entity("domain.Entities.Pnp.PnpMGeneral", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long?>("DeletedFlag")
                        .HasColumnType("bigint")
                        .HasColumnName("deleted_flag");

                    b.Property<string>("Typeevent")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("typeevent");

                    b.Property<string>("Typegroup")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("typegroup");

                    b.Property<string>("Typename")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("typename");

                    b.Property<string>("Typevalue")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("typevalue");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("pnp_m_general", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
