@WebAPI_HostAddress = https://localhost:7095
POST {{WebAPI_HostAddress}}/api/v1/pdpa-consent-get
Content-Type: application/json

{
  "pageNumber": 1,
  "pageSize": 5,
  "filterType": 0,
  "filterValue": ""
}

###

POST {{WebAPI_HostAddress}}/api/v1/pdpa-consent-create
Content-Type: application/json

{
  "conCode": "string",
  "status": 0,
  "version": "string",
  "titleTh": "string",
  "titleEn": "string",
  "titleZh": "string",
  "descriptionTh": "string",
  "descriptionEn": "string",
  "descriptionZh": "string"
}

###
